# Generated by Django 2.0.4 on 2018-04-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactForm', '0002_contactform_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='help_type',
            field=models.CharField(choices=[('Help', 'Help'), ('Bug Report', 'Bug Report'), ('Just Saying Hi!', 'Just Saying Hi!'), ('Request Access', 'Request Access')], default='Help', max_length=20),
        ),
    ]
